### ISSUE TITLE
Application should have default command line arguments defined.

### ISSUE THREAD

**Issue by jamiebegin** [mmgoodnow/cross-seed#216]
I'm attempting to launch a Docker container using the sample config in the wiki:
```
version: "2.1"
services:
    cross-seed:
        image: mmgoodnow/cross-seed
        container_name: cross-seed
        user: 1000:1000
        volumes:
            - /path/to/config/folder:/config
            - /path/to/rtorrent_sess:/torrents:ro
            - /path/to/output/folder:/output
        ports:
            - 2468:2468
        command: daemon
```
The container just dies with `error: required option '-i, --torrent-dir <dir>' not specified` in the Docker log. 

I'm specifying a valid path to the volume in the Docker compose file. The application should check for the default values before complaining. Using `command: daemon -i /torrents -s /output` fixes the errors, but isn't very elegant.
