### ISSUE TITLE
Recently ignoring config settings

### ISSUE THREAD

**Issue by TRaSH-** [mmgoodnow/cross-seed#269]
I noticed that recently it's ignoring my config settings,
I use the following setting that get's triggered by a cron once in 24 hours, It should ignore everything what's older then 7 Days.

```js
module.exports = {
	delay: 60,
	torznab: [
					"http://prowlarr:9696/30/api?apikey=API&tracker=BeyondHD",
					"http://prowlarr:9696/37/api?apikey=API&tracker=Blutopia",
					"http://prowlarr:9696/35/api?apikey=API&tracker=FileList",
					"http://prowlarr:9696/25/api?apikey=API&tracker=HDBits",
					"http://prowlarr:9696/21/api?apikey=API&tracker=PassThePopcorn",
					"http://prowlarr:9696/38/api?apikey=API&tracker=TorrentLeech",
					"http://prowlarr:9696/17/api?apikey=API&tracker=HD-Torrents",
					"http://prowlarr:9696/16/api?apikey=API&tracker=IPTorrents",
					"http://prowlarr:9696/28/api?apikey=API&tracker=PrivateHD",
	],
	torrentDir: "/input",
	outputDir: "/output",
	includeEpisodes: true,
	searchAll: true,
	fuzzySizeThreshold: 0.02,
	excludeOlder: 10080,
	excludeRecentSearch: undefined,
	action: "inject",
	rtorrentRpcUrl: undefined,
	qbittorrentUrl: "http://admin:adminadmin@qbittorrent-vpn-movies:8080",
	notificationWebhookUrl: "https://dev.notifiarr.com/api/v1/notification/crossSeed/API",
};
```

But it's ignoring these settings and doing a search all every time, I know you can add the options to the command line that get's triggered but it used to follow the config settings.

The verbose logs is giving the following

```js
2022-06-10 00:15:02 [36mverbose[39m: [configdump] {
  torznab: [
    'http://prowlarr:9696/30/api?apikey=[REDACTED]&tracker=BeyondHD',
    'http://prowlarr:9696/37/api?apikey=[REDACTED]&tracker=Blutopia',
    'http://prowlarr:9696/35/api?apikey=[REDACTED]&tracker=FileList',
    'http://prowlarr:9696/25/api?apikey=[REDACTED]&tracker=HDBits',
    'http://prowlarr:9696/21/api?apikey=[REDACTED]&tracker=PassThePopcorn',
    'http://prowlarr:9696/38/api?apikey=[REDACTED]&tracker=TorrentLeech',
    'http://prowlarr:9696/17/api?apikey=[REDACTED]&tracker=HD-Torrents',
    'http://prowlarr:9696/16/api?apikey=[REDACTED]&tracker=IPTorrents',
    'http://prowlarr:9696/28/api?apikey=[REDACTED]&tracker=PrivateHD'
  ],
  torrentDir: '/input',
  outputDir: '/output',
  includeNonVideos: false,
  includeEpisodes: true,
  fuzzySizeThreshold: 0.02,
  excludeOlder: '10s',
  verbose: false,
  action: 'inject',
  qbittorrentUrl: 'http://admin:[REDACTED]@qbittorrent-vpn-movies:8080',
  notificationWebhookUrl: 'https://dev.notifiarr.com/api/v1/notification/crossSeed/API',
  delay: 60
}
2022-06-10 00:15:02 [32minfo[39m: Validating your configuration...
2022-06-10 00:15:02 [36mverbose[39m: [qbittorrent] Making request to /torrents/createTags with body tags=cross-seed
2022-06-10 00:15:02 [32minfo[39m: Your configuration is valid!
2022-06-10 00:15:04 [36mverbose[39m: [prefilter] 687 duplicates not selected for searching
```
What's weird is that the exludeOlder is set to 10s here

I'm using the following docker-compose

```yml
version: "3"
services:
  Xseed-movies:
    command:
      - search
    container_name: Xseed-movies
    entrypoint:
      - cross-seed
    environment:
      - PGID=100
      - TZ=Europe/Berlin
      - HOST_OS=Unraid
      - HOST_CONTAINERNAME=Xseed-movies
      - PUID=99
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NODE_VERSION=14.19.3
      - YARN_VERSION=1.22.19
      - CONFIG_DIR=/config
      - DOCKER_ENV=true
    hostname: 094bfb499110
    image: mmgoodnow/cross-seed
    ipc: private
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:2468]
      org.opencontainers.image.created: 2022-06-08T06:25:15.740Z
      org.opencontainers.image.description: Fully-automatic cross-seeding with Torznab
      org.opencontainers.image.licenses: Apache-2.0
      org.opencontainers.image.revision: 8d933e7762f3ab1fc6508bce513b011bb2fe88f1
      org.opencontainers.image.source: https://github.com/mmgoodnow/cross-seed
      org.opencontainers.image.title: cross-seed
      org.opencontainers.image.url: https://github.com/mmgoodnow/cross-seed
      org.opencontainers.image.version: version-4.0.1
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 50m
    networks:
      - skynet
    ports:
      - 2468:2468/tcp
    volumes:
      - /mnt/fastdrive/appdata/Xseed-movies:/config:rw
      - /mnt/./fastdrive/appdata/qbittorrent-vpn-movies/data/BT_backup/:/input:rw
    working_dir: /usr/src/app
networks:
  skynet:
    external: true
```
