### ISSUE TITLE
File exists but not injecting into qbittorrent

### ISSUE THREAD

**Issue by ajhorvath20** [mmgoodnow/cross-seed#72]
Hi, 

I am seeing this in the log `today at 19:03:54  Found File.2021.1080p.mkv on tracker - exists` and I can also see it in my cache folder but this file was not injected into `qbittorrent`

Thats my compose
```
  cross-seed:
    image: mmgoodnow/cross-seed
    hostname: ${DOCKERHOSTNAME}
    ports:
      - 2468:2468
    container_name: cross-seed
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    restart: unless-stopped
    command: search
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/cross-seed:/config
      - ${DOCKERCONFDIR}/qbittorrent/data/BT_backup:/input:ro
      - ${DOCKERSTORAGEDIR}/data/.torrents:/output
```
And thats my config file
```
module.exports = {
	configVersion: 1,

	jackettServerUrl: "http://192.168.1.167:9117",
	jackettApiKey: "myapikey",

	delay: 60,

	trackers: ["tracker1", "tracker2", "tracker3", "tracker4"],

	torrentDir: "/input",

	outputDir: "/output",

	includeEpisodes: false,

	searchAll: false,

	action: "inject",

	rtorrentRpcUrl: undefined,

	qbittorrentUrl: "http://username:password@192.168.1.167:8080",
};
```
Thanks
